//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BLZServiceSOAP11Binding", Namespace="http://thomas-bayer.com/blz/")]
public partial class BLZService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getBankOperationCompleted;
    
    /// <remarks/>
    public BLZService() {
        this.Url = "http://www.thomas-bayer.com/axis2/services/BLZService";
    }
    
    /// <remarks/>
    public event getBankCompletedEventHandler getBankCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://thomas-bayer.com/blz/", ResponseNamespace="http://thomas-bayer.com/blz/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("details")]
    public detailsType getBank(string blz) {
        object[] results = this.Invoke("getBank", new object[] {
                    blz});
        return ((detailsType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetBank(string blz, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getBank", new object[] {
                    blz}, callback, asyncState);
    }
    
    /// <remarks/>
    public detailsType EndgetBank(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((detailsType)(results[0]));
    }
    
    /// <remarks/>
    public void getBankAsync(string blz) {
        this.getBankAsync(blz, null);
    }
    
    /// <remarks/>
    public void getBankAsync(string blz, object userState) {
        if ((this.getBankOperationCompleted == null)) {
            this.getBankOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBankOperationCompleted);
        }
        this.InvokeAsync("getBank", new object[] {
                    blz}, this.getBankOperationCompleted, userState);
    }
    
    private void OngetBankOperationCompleted(object arg) {
        if ((this.getBankCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getBankCompleted(this, new getBankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thomas-bayer.com/blz/")]
public partial class detailsType {
    
    private string bezeichnungField;
    
    private string bicField;
    
    private string ortField;
    
    private string plzField;
    
    /// <remarks/>
    public string bezeichnung {
        get {
            return this.bezeichnungField;
        }
        set {
            this.bezeichnungField = value;
        }
    }
    
    /// <remarks/>
    public string bic {
        get {
            return this.bicField;
        }
        set {
            this.bicField = value;
        }
    }
    
    /// <remarks/>
    public string ort {
        get {
            return this.ortField;
        }
        set {
            this.ortField = value;
        }
    }
    
    /// <remarks/>
    public string plz {
        get {
            return this.plzField;
        }
        set {
            this.plzField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getBankCompletedEventHandler(object sender, getBankCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getBankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getBankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public detailsType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((detailsType)(this.results[0]));
        }
    }
}
